### ISSUE TITLE
Information at beguinning of results

### ISSUE THREAD

**Issue by Quoniam** [Patent2net/P2N#18]
Informations at the beguinning of the result HTML page is relevant

Informations:

    Data directory: Masculinity
    Request: (((ta = masculin* or ta = viril*) or ta = manhood*) or ta = manlin*) OR (ta = men and ta = psycholog*)
    Number of patents retrieved: 851
    Family lenght: 948
    Gathering date: 09, Jul 2017
    Description:
    FamiliesDescription: 5 (FR)   92 (EN)   1 (ZH)   14 (DE)   1 (KO)   12 (ES)  
    Abstract: 30 (FR)   5 (DE)   795 (EN)   149 (OL)  
    Claims:
    FamiliesAbstract: 66 (FR)   9 (DE)   544 (EN)   105 (OL)  
    FamiliesClaims: 4 (FR)   91 (EN)   1 (ZH)   11 (DE)   1 (KO)   12 (ES)  

But they could be better grouped

Informations:

    Data directory: Masculinity
    Request: (((ta = masculin* or ta = viril*) or ta = manhood*) or ta = manlin*) OR (ta = men and ta = psycholog*)
    Gathering date: 09, Jul 2017
    Number of patents retrieved: 851
    Abstract: 30 (FR)   5 (DE)   795 (EN)   149 (OL)  
    Description:
    Claims:
    Family lenght: 948
    FamiliesAbstract: 66 (FR)   9 (DE)   544 (EN)   105 (OL)  
    FamiliesDescription: 5 (FR)   92 (EN)   1 (ZH)   14 (DE)   1 (KO)   12 (ES)  
    FamiliesClaims: 4 (FR)   91 (EN)   1 (ZH)   11 (DE)   1 (KO)   12 (ES) 

for example

**Comment by rfaga** [comment]
Fixed https://github.com/Patent2net/P2N/commit/af3be1fa43e7167a50e587a14bf675c692a6473d
