### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Quoniam** [Patent2net/P2N#19]
Is it possible to Jinja2 (thanks Roberto) to test if file exist before writing the link in Results HTML page?

i.e. no claims in patent universe, to avoid all the 404 error in results

**Comment by rfaga** [comment]
FIxed with https://github.com/Patent2net/P2N/commit/acb91190e946dc4742de1646fd8fac6cca2b9435 and https://github.com/Patent2net/P2N/commit/acb91190e946dc4742de1646fd8fac6cca2b9435
