### ISSUE TITLE
Mind mapping links

### ISSUE THREAD

**Issue by cvanderlei** [Patent2net/P2N#5]
As a suggestion from Professor Luc, it will be created a hyperlink in each node of mind mapping to the EPO Search bringing other patents with the same classification of the reference node.

**Comment by Quoniam** [comment]
super!!! May be better with low frequency IPC nodes?

**Comment by cvanderlei** [comment]
For an initial test, I put it in all final nodes (IPC11)... It's too easy to put it in other levels, but, the search brings too many registers in Espacenet. 
For while, I think it's better to use de Zipf law in another way, for example changing something in the visual presentation of the low frequency nodes. 
Let's try those options?
I'm releasing today a 32 bits version whith the link to Espacenet for testing only.

**Comment by Quoniam** [comment]
Of course... only IPC11 ... I will begin teste soon..
