### ISSUE TITLE
Another Familly Gathering error

### ISSUE THREAD

**Issue by Quoniam** [Patent2net/P2N#7]
In that case... Familly Claims and description where not gathered... And have the above error.
all necessary files to reproduce the case are provided.
Regards

[Drone Errors.txt](https://github.com/Patent2net/P2N/files/658913/Drone.Errors.txt)
[drone.cql.txt](https://github.com/Patent2net/P2N/files/658914/drone.cql.txt)
[Drone ErrorsLogs.zip](https://github.com/Patent2net/P2N/files/658915/Drone.ErrorsLogs.zip)

Traceback (most recent call last):
  File "<string>", line 229, in <module>
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherContentsv2-Iramuteq\out00-PYZ.pyz\P2N_Lib", line 2293, in MakeIram2
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherContentsv2-Iramuteq\out00-PYZ.pyz\P2N_Lib", line 1676, in UniClean
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 31: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 126, in <module>

**Comment by cvanderlei** [comment]
Problem found... testing the solution.

**Comment by Quoniam** [comment]
Another Pb... That I think similar... in another case,
the kidney case ... is a fusion of kidney1 and Kidney2

Fusion of requests is described in the [dokuwiki](http://patent2netv2.vlab4u.info/dokuwiki/doku.php?id=user_manual:fusion)

[kidney.cql.txt](https://github.com/Patent2net/P2N/files/663800/kidney.cql.txt)
[kidney1.cql.txt](https://github.com/Patent2net/P2N/files/663801/kidney1.cql.txt)
[kidney2.cql.txt](https://github.com/Patent2net/P2N/files/663802/kidney2.cql.txt)

Traceback (most recent call last):
  File "<string>", line 229, in <module>
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherContentsv2-Iramuteq\out00-PYZ.pyz\P2N_Lib", line 2293, in MakeIram2
  File "C:\_lab\P2N\Patent2Net\build\OPSGatherContentsv2-Iramuteq\out00-PYZ.pyz\P2N_Lib", line 1676, in UniClean
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 126, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 6: ordinal not in range(128)
kidney.cql  processed

**Comment by cvanderlei** [comment]
The solution to the error in line 1676 of P2N_Lib was found. 
There still a problem that generate the error in 
File "", line 126, in 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 6: ordinal not in range(128)

Due several try/except in the code, it is very hard to find where this problem really occurs.

**Comment by cvanderlei** [comment]
Trying to fix this, I am changing all calls to the unicode() function with the parameter errors='ignore'.
This parameter will avoid error messages when it is not possible to convert a character.

**Comment by cvanderlei** [comment]
I am having several "IOError" message and the systme doesn't work.
It's very strange, I already tried several things, like changing direcotry, recompile, restart the machine... but nothing work. 
Could be an Espacenet problem?

**Comment by cvanderlei** [comment]
The system is working again, but the bug is not solved yet.
As I said before, P2N have too much try/except. The correct way to use this is being specific, just using except with the error code that we want to bypass. When we use except without error code, any exception is raised to the level above, but if the level above have another generic try/except, it turns almost impossible to know where the problem really occurs. 
To make P2N more consistent, one day we hve to correct all try/except... it's a big job.

**Comment by Quoniam** [comment]
For me Drone solved, no error when running from crash...
But Kidney case , unfortunately, ...

done saving requete, replaced by ..\REQUESTS\kidney.cql
C:\Users\Public\Softs\LUCP2N~1\PATENT~1\dateutil\parser.py:330: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "<string>", line 330, in <module>
TypeError: 'NoneType' object is not iterable
C:\Users\Public\Softs\LUCP2N~1\PATENT~1\dateutil\parser.py:330: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

**Comment by cvanderlei** [comment]
Fixed. A built version is available for testing in quoniam.dynip.sapo.pt - Softs/Celso-P2N e Celso-P2N(x86).
